# docker-compose.yml
version: '3.9'

services:

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

    depends_on:
      - db

  db:
    image: postgres:16
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "pg_data_nationalization:/var/lib/postgresql/data/"
      - "./.sql:/docker-entrypoint-initdb.d"


  adminer:
    image: adminer
    restart: "unless-stopped"
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  pg_data_nationalization:
